### ISSUE TITLE
Link to the blog post in the README.md

### ISSUE THREAD

**Issue by travis-r6s** [codetalkio/Haskell-Electron-app#1]
needs to be changed...

from
https://codetalk.io/posts/2016-05-10-using-electron-with-haskell.html
to
https://codetalk.io/posts/2016-05-1**1**-using-electron-with-haskell.html

**Comment by Tehnix** [comment]
Ah, thanks for catching this! I'll update the link, and look into updating the code for the newest versions this weekend :) (probably not much code change though).
