### ISSUE TITLE
backend build failure

### ISSUE THREAD

**Issue by jamesdbrock** [codetalkio/Haskell-Electron-app#2]
The backend `stack build` fails with error

    Configuring semigroupoids-5.0.1...
    setup: At least the following dependencies are missing:
    tagged >=0.8.5 && <1 && ==0.8.4

but `stack build` succeeds if I use `resolver: lts-6.25`.

**Comment by Tehnix** [comment]
Huh, that's interesting. I wonder if the library was removed from stackage?

Anyways, I'll update the resolver to `lts-6.25`, since it seems to work :) Thanks for testing it out!
